### PR TITLE
restart the HTTP server after an exception

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by sinkingsugar** [comment]
Defects should still be treated as fatal imho tho.

**Comment by stefantalpalaru** [comment]
I want this to be a "die hard" thread.

**Comment by arnetheduck** [comment]
+1 for not catching defects - after a defect, the (whole) application is in a undefined state because memory and state corruptions are typical for defects

**Comment by stefantalpalaru** [comment]
Fine, I'll give in to peer pressure :-)

**Pull request merged**
