### PR TITLE
StatsD and Carbon metric exporting

### PR DESCRIPTION
**Pull request by stefantalpalaru**
A very primitive networking setup, for now. Has to be improved before merging.

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
It now has all the features I wanted:
- pushing metrics is non-blocking by placing the data in an unlimited queue inside a channel
- a separate thread handles networking by reusing one socket per backend and reconnecting automatically after `send()` errors, but only after a minimum waiting interval between connection attempts

**Comment by arnetheduck** [comment]
> pushing metrics is non-blocking by placing the data in an unlimited queue inside a channel

this looks a bit like a problem: if you think about a socket, it's a bounded queue of bytes going out - as long as there's room on the queue, bytes get added, else you get `ewouldblock` (assuming you opened the socket correctly). 

This is a form of rate control, specially on UDP: if the program is producing data faster than the network can consume, it starts dropping packets. This is also the behaviour we want from metrics: they are the lowest priority traffic and if anything needs to be dropped, it's these. Another way to look at it: consider the conditions under which data is being dropped. Are there important ones where dropping is not the right thing, for metrics?

Creating a separate queue and introducing a separate thread creates quite a bit of overhead generally, both in terms of program complexity and in terms of poor behaviour when the network is not keeping up.

In my experience, it's better to let the operating system deal with queueing of such ephemeral data - in many cases, the hardware itself has a buffer onto which these packets go directly. In addition to the risk of the unbounded queue filling up memory, it's quite bad for (holistic) performance of the application to have an extra queue like this, creating pressure on memory, threading and many other resources.

**Comment by stefantalpalaru** [comment]
> This is a form of rate control, specially on UDP: if the program is producing data faster than the network can consume, it starts dropping packets. This is also the behaviour we want from metrics: they are the lowest priority traffic and if anything needs to be dropped, it's these.

You're still getting that, inside the dedicated thread that reads from a channel's queue and writes to the socket. What you're not getting is random blocking when incrementing a counter.

> Creating a separate queue and introducing a separate thread creates quite a bit of overhead generally, both in terms of program complexity and in terms of poor behaviour when the network is not keeping up.

It's the opposite. Network latency is decoupled from operations on metrics. The overhead for an API user is limited to copying data into a channel's queue.

The code complexity cost starts making sense in the case of Carbon - which defaults to TCP - and, once you pay the price for eliminating TCP latency, you might as well apply it to UDP.

**Comment by arnetheduck** [comment]
> What you're not getting is random blocking when incrementing a counter.

which random blocking? ie the idea is to open a non-blocking socket - at that point, it's really a matter of copying the data to the socket queue, or copying to the thread queue, and then copying to system socket queue. on most setups, this is a fast operation (true, slower than increasing a counter) - to before making optimizations like an extra queue and thread, take a look/measure at this simpler approach.

> The code complexity cost starts making sense in the case of Carbon - which defaults to TCP - and, once you pay the price for eliminating TCP latency, you might as well apply it to UDP.

yes, TCP is a bit of a different matter (and, you could say, a bit of a problem in this context, because it's hard to rate-control in a simple fashion) - but the situation is not dissimilar - data will be copied onto a queue and handled by a system thread when the nagle timeout runs out (since we're sending small packets) - essentially replicating the work you're doing with the thread.

it's a strength of statsd that it uses UDP in this throw-away manner - it would be sad to lose this advantage. for TCP it indeed makes sense to queue / offload to a different thread, but for another reason: we're sending metric packages but TCP is a stream-oriented protocol, so you need an collector that deals with serializing the updates into a stream atomically (as soon as we go multithreaded for real).

**Comment by arnetheduck** [comment]
with a separate thread, we also _should_ be using a bounded queue, such that if there are problems with thread, the queue should not grow out of control. in a distant future, the classic solution for these kinds of situations is a lock-free mpsc which typically are easier to implement bounded.

**Comment by stefantalpalaru** [comment]
> which random blocking?

When waiting for a TCP connection to be established, for example.

> the idea is to open a non-blocking socket

And then needing an event loop to check the TCP connection status? With some event loop timer to retry the connection? I don't want that complexity. Blocking sockets in a separate thread are much easier to reason about and debug.

> it's really a matter of copying the data to the socket queue, or copying to the thread queue, and then copying to system socket queue

That's what it's doing right now: there's a channel queue, then a Nim socket queue, then an OS socket queue.

> with a separate thread, we also should be using a bounded queue, such that if there are problems with thread, the queue should not grow out of control

I'm not worried about the channel queue growing too large, because data is continuously read from it and dropped during the reconnection wait period (`send()` fails with ENOTCONN, `reconnectSocket()` returns early and we're back to draining the channel).

For the scenario in which we can consistently produce metrics faster than we can send them over a connected socket, I want some statistics before bounding the channel queue size and moving to `Channel.trySend()` so I can drop metrics in the caller. It just seems unrealistic to me right now.

> we're sending metric packages but TCP is a stream-oriented protocol, so you need an collector that deals with serializing the updates into a stream atomically

The stream is at a lower level. We're fine sending atomic metric data on the same socket. It won't get garbled in any way at the destination. Since these are just metrics, we don't care how quickly they reach the backends so it's not worth optimising that by combining them before sending.

**Comment by arnetheduck** [comment]
> When waiting for a TCP connection to be established, for example.
> And then needing an event loop to check the TCP connection status? With some event loop timer to retry the connection? I don't want that complexity. Blocking sockets in a separate thread are much easier to reason about and debug.

with udp, you don't need an event loop and there's no blocking.. you open the socket and that's it, there's no network activity involved.

and yes, as mentioned, adding TCP at all to the mix adds complexity that generally is unwanted for the fire-and-forget, mindset of metrics - `statsd` is UDP for a reason and we're discarding that reason and making it more difficult than it has to be, like this, with all the extra queue copying.

blocking sockets are really a thing of the past - you can't stop the application for example if it's stuck in a blocking call, meaning you can't empty the unbounded queue. it's a broken and unsafe architecture. if the metrics server stops reading bytes, you block until the socket goes down which might take a long while, with memory going up all the time on your own queue. you will not be able to test for this behaviour, instead it will hit a user eventually when they run the thing on a real network / non-locally and report a hard-to-debug memory growth issue.

> We're fine sending atomic metric data

UDP sockets are thread safe by design, TCP are not - you need synchronization if you want to send data on a TCP socket. that's why people add additional application-level queues generally in multithreaded socket applications - then they run an event loop with non-blocking sockets because blocking has several pathological behaviours.

**Comment by stefantalpalaru** [comment]
> you can't stop the application for example if it's stuck in a blocking call

You can, all those calls are interruptible by signals.

> statsd is UDP for a reason

They also support TCP: https://github.com/statsd/statsd/blob/master/docs/server.md

I see the beauty in firing UDP packets and moving away quickly, but that's not how a complete support looks like.

> with memory going up all the time on your own queue

I just hit that in an artificial test, so I moved to a fixed-size channel buffer and `Channel.trySend()` to quickly drop metrics when that buffer is full.

> if the metrics server stops reading bytes, you block until the socket goes down which might take a long while

> blocking has several pathological behaviours.

Let's test it. "flood.nim":

```nim
import metrics, net, times

when defined(metrics):
  addExportBackend(
    metricProtocol = CARBON,
    netProtocol = TCP,
    address = "127.0.0.1",
    port = Port(2003)
  )

declareCounter flooder, "artificial load test"

var
  start = getTime().toUnix() # timestamp in seconds
  last = start
  current: int64
  metricsPerSecond: int64

while true:
  flooder.inc()
  metricsPerSecond.inc()
  current = getTime().toUnix()
  if current > last:
    last = current
    echo current - start, ", ", metricsPerSecond
    metricsPerSecond = 0
```
Compile it with `-d:release`. A Carbon daemon is started in another terminal with `carbon-cache.py --config=/etc/carbon/carbon.conf --debug --logfile=- start`. Now we start `./flood` and stop the Carbon daemon with Ctrl+C after 10 seconds, wait a few seconds and start it again:

```text
$ ./flood 
1, 234713
2, 481478
3, 2682752
4, 2735841
5, 2495824
6, 2648823
7, 2386630
8, 2675252
9, 2558391
10, 2478684
11, 3088466 # the Carbon daemon was killed. Rate going up.
12, 3044933
13, 3085287
14, 3115479
15, 3041847
16, 3143348
17, 3072420
18, 3090672
19, 3061880
20, 3065594
21, 2324081 # a few seconds ago, the Carbon daemon was restarted. Now we reconnected.
22, 1031780
23, 2349271 
24, 2351855
25, 2649465
26, 2585732
27, 2184533
```

As you can see, there are no issues when backends go down on us. Tell me again why I should introduce non-blocking sockets and increase the complexity by an order of magnitude or so.

---

P.S.: fun fact - Graphite devs reimplemented the RRD format and called it "Whisper": https://graphite.readthedocs.io/en/latest/whisper.html

**Pull request merged**
